#!/bin/sh
benchmarks=true
if [ ! `ocamlfind ocamldep -package unmark` ] ; then
    echo "Skipping benchmarks"
    benchmarks=false
fi
topkg build -- --with-unix true --with-lwt true --benchmarks ${benchmarks} --examples true
